language: ruby

rvm:
  - 2.1.0
  - 2.2.3
  - ruby-head

before_install:
  - sudo apt-get install libtokyocabinet-dev -y

script: bundle exec ruby test/run-test.rb

matrix:
  allow_failures:
    - rvm: ruby-head
